name: Deploy to AWS Lambda on Release

on:
  release:
    types: [published]

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_LAMBDA_FUNCTION_NAME: ${{ vars.AWS_LAMBDA_FUNCTION_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Extract version from tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Deploying version: $VERSION"
        
    - name: Update version file
      run: |
        echo '"""Version information."""' > version.py
        echo '__version__ = "${{ env.VERSION }}"' >> version.py
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install boto3 # For AWS SDK
        
    - name: Create deployment package
      run: |
        # Create zip file containing the lambda function and dependencies
        zip -j lambda_function.zip lambda_function.py version.py
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Deploy to Lambda
      run: |
        # Update Lambda function code
        aws lambda update-function-code \
          --function-name ${{ env.AWS_LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://lambda_function.zip
          
        # Update Lambda function configuration
        aws lambda update-function-configuration \
          --function-name ${{ env.AWS_LAMBDA_FUNCTION_NAME }} \
          --description "Fastly Logs Lambda v${{ env.VERSION }}" 